[[1, 0], [0, 0], [1, 1], [0, 0], [0, 0]] spawn EAS_fnc_adjustVolume;
playMusic "EAS_ep001_intro";
titleText ["What you are about to witness are key accounts from the Altis Intervention Crisis.\nViewer discretion is advised.", "BLACK FADED", -1];
sleep 10;
titleText ["March 2035 - Task force spartan arrives just a few miles off the coast of the small and unknown Mediterranean island of Altis.", "BLACK FADED", -1];
sleep 9;
titleText ["A full-scale military intervention has been ordered by president Johnson with the objective of securing the region from AAF control.", "BLACK FADED", -1];
sleep 9;
titleText ["Members of the US Naval Special Warfare Command are ordered to reinforce FIA positions.", "BLACK FADED", -1];
sleep 6;
titleText ["While the US Navy conduct a large scale bombing campaign on key military and industrial targets", "BLACK FADED", -1];
sleep 6;
titleText ["with the hope of crippling the AAF by showcasing the awesome extent of American firepower!", "BLACK FADED", -1];
sleep 5;
titleText ["US command expects victory in just 4 days!", "BLACK IN", 8];